### PR TITLE
Filtering by dimensions which include / in name does not work in generic scraper

### LINKED ISSUE #1266: Filtering by dimensions which include / in name does not work in generic scraper
Filtering by dimensions which include / in name does not work as reported in https://github.com/tomkerkhove/promitor/issues/1248#issuecomment-687727795 by @renebarbosafl:

> Example:
> 
> ```yaml
> - name: azure_app_insights_api_depend_fail
>     description: "Web Application Dependency Failures"
>     resourceType: Generic
>     azureMetricConfiguration:
>       metricName: dependencies/failed
>       dimension:
>         name: dependency/target
>       aggregation:
>         type: Count
>     resources:
>     - resourceUri: Microsoft.Insights/Components/Insights-API
>       filter: 'dependency/resultCode eq 500'
>       resourceGroupName: ResourceGroup`
> ```
> 
> Expected behavior: We want to exclude 4xx result codes and only store 5xx.
> Current behavior: Everything is being stored (Filter is being ignored).

### PR DESCRIPTION
**Pull request by tomkerkhove**
Both metrics work, unfortunately, I don't have any other response codes to test with.

```
# HELP promitor_demo_app_insights_dependency_duration Average dependency duration per dependency type
# TYPE promitor_demo_app_insights_dependency_duration gauge
promitor_demo_app_insights_dependency_duration{resource_group="docker-hub-metrics",subscription_id="0f9d7fea-99e8-4768-8672-06a28514f77e",resource_uri="subscriptions/0f9d7fea-99e8-4768-8672-06a28514f77e/resourceGroups/docker-hub-metrics/providers/Microsoft.Insights/Components/docker-hub-metrics",instance_name="Microsoft.Insights/Components/docker-hub-metrics",dependency_type="Http"} 540.75 1599666014691
# HELP promitor_demo_app_insights_dependency_duration_200_OK Average dependency duration per dependency type
# TYPE promitor_demo_app_insights_dependency_duration_200_OK gauge
promitor_demo_app_insights_dependency_duration_200_OK{resource_group="docker-hub-metrics",subscription_id="0f9d7fea-99e8-4768-8672-06a28514f77e",resource_uri="subscriptions/0f9d7fea-99e8-4768-8672-06a28514f77e/resourceGroups/docker-hub-metrics/providers/Microsoft.Insights/Components/docker-hub-metrics",instance_name="Microsoft.Insights/Components/docker-hub-metrics"} 540.75 1599666014627
```

Fixes #1266

### CODE REVIEW

**Comment by tomkerkhove** [comment]
@renebarbosafl the CI will spit out an image, would you mind testing that one?

**Comment by tomkerkhove** [comment]
From what I'm seeing it works, feel free to confirm.

**Comment by renebarbosafl** [comment]
Hi Tom, 

It doesn't seem to be working (or maybe I did something wrong here), with filter:

ae29b07056d3d",resource_uri="subscriptions/c1cbcf63-fd33-40b4-9672-e29b07056d3d/resourceGroups/SuperPratico-GO/providers/Microsoft.Insights/Components/GO-Insights-API",instance_name="Microsoft.Insights/Components/GO-Insights-API",dependency_target="superpraticogo.blob.core.windows.net"} 9106

It's a storage account, we're scraping 9106 erros but there aren't any HTTP-500 errors there, only 40x.
I've used this config:

```yaml
  - name: test
    description: "Just a test, please ignore"
    resourceType: Generic
    azureMetricConfiguration:
      metricName: dependencies/failed
      dimension:
        name: dependency/target
      aggregation:
        type: Count
    resources:
    - resourceUri: Microsoft.Insights/Components/GO-Insights-API
      resourceGroupName: SuperPratico-GO
      filter: dependency/resultCode eq '500'
```

**Comment by tomkerkhove** [comment]
> It doesn't seems to be working (or maybe I did something wrong here), with filter:
> 
> ae29b07056d3d",resource_uri="subscriptions/c1cbcf63-fd33-40b4-9672-e29b07056d3d/resourceGroups/SuperPratico-GO/providers/Microsoft.Insights/Components/GO-Insights-API",instance_name="Microsoft.Insights/Components/GO-Insights-API",dependency_target="superpraticogo.blob.core.windows.net"} 9106
> 
> It's a storage account, we're scraping 9106 erros but there aren't any HTTP-500 errors there, only 40x.
> I've used this config:
> 
> ```yaml
>   - name: test
>     description: "Just a test, please ignore"
>     resourceType: Generic
>     azureMetricConfiguration:
>       metricName: dependencies/failed
>       dimension:
>         name: dependency/target
>       aggregation:
>         type: Count
>     resources:
>     - resourceUri: Microsoft.Insights/Components/GO-Insights-API
>       resourceGroupName: SuperPratico-GO
>       filter: dependency/resultCode eq '500'
> ```

Odd, could you maybe add an additional metric without the filter based on [this image](https://github.com/tomkerkhove/promitor/pull/1273#issuecomment-690027754) so we can compare both and include a screenshot of Metrics Explorer split by result code?

Feel free to send over the logs as well because this worked for me yesterday evening so happy to dig deeper.

**Comment by tomkerkhove** [comment]
I did a more thorough test and will merge it given everything looks ok.

Metrics config:
```yaml
metrics:
  - name: promitor_demo_app_insights_dependency_duration
    description: "Average dependency duration per dependency type"
    resourceType: Generic
    azureMetricConfiguration:
      metricName: dependencies/duration
      aggregation:
        type: Average
        interval: 00:30:00
    resources:
    - resourceUri: Microsoft.Insights/Components/promitor-telemetry
      resourceGroupName: promitor
  - name: promitor_demo_app_insights_dependency_duration_200_OK
    description: "Average dependency duration per dependency type"
    resourceType: Generic
    azureMetricConfiguration:
      metricName: dependencies/duration
      aggregation:
        type: Average
        interval: 00:30:00
    resources:
    - resourceUri: Microsoft.Insights/Components/promitor-telemetry
      resourceGroupName: promitor
      filter: dependency/resultCode eq '200'
  - name: promitor_demo_app_insights_dependency_duration_429_TooManyRequests
    description: "Average dependency duration per dependency type"
    resourceType: Generic
    azureMetricConfiguration:
      metricName: dependencies/duration
      aggregation:
        type: Average
        interval: 00:30:00
    resources:
    - resourceUri: Microsoft.Insights/Components/promitor-telemetry
      resourceGroupName: promitor
      filter: dependency/resultCode eq '429'
  - name: promitor_demo_app_insights_dependency_duration_500_InternalServerError
    description: "Average dependency duration per dependency type"
    resourceType: Generic
    azureMetricConfiguration:
      metricName: dependencies/duration
      aggregation:
        type: Average
        interval: 00:30:00
    resources:
    - resourceUri: Microsoft.Insights/Components/promitor-telemetry
      resourceGroupName: promitor
      filter: dependency/resultCode eq '500'
```

Output with a clear separation and average per status code:
```
# HELP promitor_demo_app_insights_dependency_duration Average dependency duration per dependency type
# TYPE promitor_demo_app_insights_dependency_duration gauge
promitor_demo_app_insights_dependency_duration{resource_group="promitor",subscription_id="0f9d7fea-99e8-4768-8672-06a28514f77e",resource_uri="subscriptions/0f9d7fea-99e8-4768-8672-06a28514f77e/resourceGroups/promitor/providers/Microsoft.Insights/Components/promitor-telemetry",instance_name="Microsoft.Insights/Components/promitor-telemetry"} 49723.134146341465 1599804600970
# HELP promitor_demo_app_insights_dependency_duration_200_OK Average dependency duration per dependency type
# TYPE promitor_demo_app_insights_dependency_duration_200_OK gauge
promitor_demo_app_insights_dependency_duration_200_OK{resource_group="promitor",subscription_id="0f9d7fea-99e8-4768-8672-06a28514f77e",resource_uri="subscriptions/0f9d7fea-99e8-4768-8672-06a28514f77e/resourceGroups/promitor/providers/Microsoft.Insights/Components/promitor-telemetry",instance_name="Microsoft.Insights/Components/promitor-telemetry"} 44422.30107526882 1599804601552
# HELP promitor_demo_app_insights_dependency_duration_429_TooManyRequests Average dependency duration per dependency type
# TYPE promitor_demo_app_insights_dependency_duration_429_TooManyRequests gauge
promitor_demo_app_insights_dependency_duration_429_TooManyRequests{resource_group="promitor",subscription_id="0f9d7fea-99e8-4768-8672-06a28514f77e",resource_uri="subscriptions/0f9d7fea-99e8-4768-8672-06a28514f77e/resourceGroups/promitor/providers/Microsoft.Insights/Components/promitor-telemetry",instance_name="Microsoft.Insights/Components/promitor-telemetry"} 50023.752808988764 1599804601017
# HELP promitor_demo_app_insights_dependency_duration_500_InternalServerError Average dependency duration per dependency type
# TYPE promitor_demo_app_insights_dependency_duration_500_InternalServerError gauge
promitor_demo_app_insights_dependency_duration_500_InternalServerError{resource_group="promitor",subscription_id="0f9d7fea-99e8-4768-8672-06a28514f77e",resource_uri="subscriptions/0f9d7fea-99e8-4768-8672-06a28514f77e/resourceGroups/promitor/providers/Microsoft.Insights/Components/promitor-telemetry",instance_name="Microsoft.Insights/Components/promitor-telemetry"} 53730.9625 1599804601350
```

**Pull request merged**
