### PR TITLE
chore(deps): update prometheus.client

### LINKED ISSUE #1772: Upgrade to latest versions of Prometheus.Client packages 📦
We should follow-up on @sanych-sun's suggestion in https://github.com/prom-client-net/prom-client-dependencyinjection/issues/20#issuecomment-918818066

### PR DESCRIPTION
**Pull request by phnx47**
Fixes #1772

@tomkerkhove I can't remove `services.BuildServiceProvider();` without completely rewrite schedule logic. Right now I just updated `Prometheus.Client` and use `DefaultCollectorRegistry`.

Next step is rewrite scheduler or we can save it as is... For rewrite we should register Scheduler Job in  runtime, `Configure` section instead of `ConfigureServices` section, but I never used `CronScheduler.AspNetCore`. I found this https://github.com/kdcllc/CronScheduler.AspNetCore/issues/29, maybe you know how to register in runtime better.

### CODE REVIEW

**Comment by tomkerkhove** [comment]
Thanks for jumping in! Would you mind fixing the CI please?

**Comment by phnx47** [comment]
`CI - Code / Verify Codebase (pull_request)`: Seems this error - https://github.com/dorny/test-reporter/issues/168, but permissions already added

**Comment by phnx47** [comment]
`Promitor CI - Resource Discovery Agent` and `Promitor CI - Scraper Agent`: The job running on agent Azure Pipelines 3 ran longer than the maximum time of 60 minutes

**Comment by tomkerkhove** [comment]
> `CI - Code / Verify Codebase (pull_request)`: Seems this error - [dorny/test-reporter#168](https://github.com/dorny/test-reporter/issues/168), but permissions already added.
> 
> I ran it in my fork and all tests passed: [phnx47/promitor/actions/runs/3183407827/jobs/5190580488](https://github.com/phnx47/promitor/actions/runs/3183407827/jobs/5190580488) [phnx47/promitor/runs/8703462355](https://github.com/phnx47/promitor/runs/8703462355)
> 
> So, something weird, I can't re-run it here...

Re-triggered, let's see as it's odd indeed.

**Comment by tomkerkhove** [comment]
> `Promitor CI - Resource Discovery Agent` and `Promitor CI - Scraper Agent`: The job running on agent Azure Pipelines 3 ran longer than the maximum time of 60 minutes
> 
> Step: Run Integration Tests
> 
> ```
> Starting test execution, please wait...
> A total of 1 test files matched the specified pattern.
> Current metric type is not a gauge, ignoring.
> ...
> Current metric type is not a gauge, ignoring.
> ##[error]The operation was canceled.
> ```

Yes, I've just noticed so that must mean something is wrong with publishing the metrics. Quickly did https://github.com/tomkerkhove/promitor/pull/2144, let's see if it works.

**Comment by phnx47** [comment]
I did small changes, but CI wasn't triggered

**Review by tomkerkhove — APPROVED** [review]
LGTM, thanks!

**Comment by phnx47** [comment]
@tomkerkhove What about rewrite Scheduler to register jobs in runtime? I Can find time for this. It is not only for prometheus client https://learn.microsoft.com/en-us/dotnet/core/extensions/dependency-injection-guidelines#recommendations

**Comment by tomkerkhove** [comment]
Good callout - I forgot to open an issue for that. Would you mind doing that with some context please?

**Comment by phnx47** [comment]
@tomkerkhove Sure, I will do.

**Pull request merged**
