### PR TITLE
Provide better usage of `AzureMonitorClient`

### PR DESCRIPTION
**Pull request by tomkerkhove**
Provide better usage of `AzureMonitorClient` by only creating it once.

Relates to #798

### Before
image
image

### After
72669608-4ba47180-3a34-11ea-9f3e-0f5c5a5f863b
72669622-7ee70080-3a34-11ea-8f96-9074fbdaf179

### CODE REVIEW

**Comment by tomkerkhove** [comment]
@maartenba Did a bit of refactoring but didn't seem to really help.

However, it looks like there's a shitload of `HttpClient`s being created, I presume dotMemory is showing unique instance rather than (re)used ones or not?

**Comment by maartenba** [comment]
It shows unique ones, yes. Can you send me a longer run snapshot? Will have a look at it.

**Comment by tomkerkhove** [comment]
Performance analysis before & after can be downloaded from [DropBox](https://www.dropbox.com/sh/wnr8bxeebxxf8nz/AABH1Tw31ztV0TcsgTEd3GRca?dl=0)

**Comment by maartenba** [comment]
Checking "after". Looks like lots of leftover `HttpClient` instances are held in memory by `AzureMonitorClient`:

image

That in turn seems to not be disposed by `ServiceProvider` (check the right-hand side)

The AzMon libraries seem to hold a lot of these references as well, but can't really pinpoint where those come from.

Would you mind running _performance_  profiling in Timeline mode as well? That should give some more info on # calls etc.

**Comment by tomkerkhove** [comment]
You can download it [here](https://www.dropbox.com/s/mxtcdl2jwjc1yz2/Promitor.Scraper.Host.dtt?dl=0) @maartenba

**Comment by maartenba** [comment]
OK, ran through all traces, and found [`HttpClient`s are created here](https://github.com/Azure/azure-sdk-for-net/blob/45cdad6bc3f20b36220d303a44f99895bdba28b7/sdk/mgmtcommon/ClientRuntime/ClientRuntime/ServiceClient.cs#L357).

Example instance:

image

All instances:

image

Looks like there is a way to pass in an existing `HttpClient`, not sure whether that is exposed in the Azure Management API's? If yes, try passing a pre-created instance into the tree.

**Comment by tomkerkhove** [comment]
@maartenba Think it's safe to merge this or think it is not?

The issue lies in the SDK so can't do much about it, but this PR still improves it a bit.

Thougths?

**Comment by maartenba** [comment]
Think it's safe to do so, however if you figure out a way to pass in an existing `HttpClient` (which seems supported at the lower levels) you would be golden.

**Pull request merged**
