### PR TITLE
feat: Provide capability to use multiple metric dimensions

### LINKED ISSUE #1820: Provide capability to use multiple metric dimensions
### Proposal

Provide capability to use multiple metric dimensions instead of just one.

Our current metric declaration looks as following:
```yaml
- name: azure_service_bus_active_messages
    description: "The number of active messages on a service bus queue."
    resourceType: ServiceBusNamespace
    labels:
      app: promitor
      tier: messaging
    scraping:
      # Every 2 minutes
      schedule: "0 */2 * ? * *"
    azureMetricConfiguration:
      metricName: ActiveMessages
      limit: 5
      dimension:
        name: <dimension-name>
      aggregation:
        type: Total
        interval: 00:15:00
    resources: # Optional, required when no resource discovery is configured
      - namespace: promitor-messaging
        queueName: orders
```

This will change to:
```diff
- name: azure_service_bus_active_messages
    description: "The number of active messages on a service bus queue."
    resourceType: ServiceBusNamespace
    labels:
      app: promitor
      tier: messaging
    scraping:
      # Every 2 minutes
      schedule: "0 */2 * ? * *"
    azureMetricConfiguration:
      metricName: ActiveMessages
      limit: 5
      dimension: # Deprecated, use dimensions instead
        name: <dimension-name>
+     dimensions:
+     - name: <dimension-name-1>
+     - name: <dimension-name-2>
      aggregation:
        type: Total
        interval: 00:15:00
    resources: # Optional, required when no resource discovery is configured
      - namespace: promitor-messaging
        queueName: orders
```

Relates to #809

### Component

Scraper

### Contact Details

_No response_

### PR DESCRIPTION
**Pull request by amirschw**
Fixes #1820

Based on #2123 (thanks @aaronweissler and @Patrick-Eichhorn!)

### CODE REVIEW

**Comment by amirschw** [comment]
The scraper tests fail because of OTEL metrics and indeed I don't see any metrics in [Show Prometheus metrics for OpenTelemetry agent](https://dev.azure.com/tomkerkhove/Promitor/_build/results?buildId=11154&view=logs&j=30190cae-7ed8-53e7-ee11-9246d6a79584&t=dc8b9030-6556-5c8d-0ece-d3dc3e7366fc). @tomkerkhove, since the integration tests all run successfully for me locally, would you mind rerunning the test to see if it's a transient issue?

**Comment by amirschw** [comment]
Looks like it was indeed a transient issue, since it's all green now 😄

**Comment by tomkerkhove** [comment]
Can you open a companion PR for the docs please?

**Comment by tomkerkhove** [comment]
Woops, that already got merged

**Pull request merged**
