### PR TITLE
Mimetis/docs managedidentity

### PR DESCRIPTION
**Pull request by Mimetis**
Walkthrough for managed identity

**DO NOT** merge this PR until we have a definitive version of Managed Identity in Promitor

### CODE REVIEW

**Comment by tomkerkhove** [comment]
Thanks for the PR, can you merge `managed-identity` branch in your PR please?

**Comment by Mimetis** [comment]
Hey @tomkerkhove 
I was waiting for you to end the full implementation of the managed identity
Is it done ? 
The walkthrough is still based on the last version I've pushed, so not sure it's correct.

**Comment by tomkerkhove** [comment]
The PR was merged into that temporary branch, nothing related to managed identity is in master yet until the sweep was done (#1564 )

**Comment by tomkerkhove** [comment]
@Mimetis i've made a ton of changes, would you be OK to create a fresh branch off of the latest in master please?

**Comment by tomkerkhove** [comment]
Can you re-open and target master please?

**Comment by Mimetis** [comment]
Yep, I'm currently working on it :)

**Comment by Mimetis** [comment]
Not able to reopen it.
I will create a new Pull Request

**Pull request closed without merging**
