### PR TITLE
Design Review - WIP - Allow specification of metric type & Adjust metric data granularity based on metric type

### PR DESCRIPTION
**Pull request by jdevalk2**
Relates to #60

This is a proposal, I am submitting it for feedback before I put more work in it.

## Proposed Changes

General

Increase the accuracy of data read from Azure Monitor by keying on the minimum resolution that a particular metric supports.

Specific

  - On generic resource definition, allow the specification of Azure Monitor metric type (Capacity / Transactional). 
  - The resource type determines at which data granularity the Azure Monitor metric is read. The minimum resolution for Capacity metrics is 1 hour. The minimum resolution for Transactional metrics is 1 minute.
  - By reading at the minimum resolution we are reading at the maximum accuracy that Azure monitor will be able to give us at this time. There is still a window for inaccuracy due to lag, but when we read the data it reads the latest data that Azure Monitor has.
  - To get the most accurate reads,  the cron schedule would have to be 1 minute or less as well. If it is one minute, then Promitor will expose the Azure Monitor metric data as soon as its update. 

  - Secondary fix: Fix the default that is returned to 0.0 when there is no data point (Azure Monitor metric value is NULL)  0.0 is recommended by the prometheus documentation (or NaN if 0 is difficult)

Currently the new reading functionality is in DataPointReader. It is keyed off of the presence of MetricType in configuration. If there is no metric type, the old behaviour is done.

Example config
```
metrics: 
- name: "storage_transaction_total"
  description: "Storage transaction count"
  resourceType: "Generic"
  resourceUri: "Microsoft.Storage/storageAccounts/storageaccountname/blobServices/default"
  azureMetricConfiguration:
    metricType: "Transactional"
    metricName: "Transactions"
    aggregation: "Total"
```

### CODE REVIEW

**Comment by tomkerkhove** [comment]
Thank you for the PR! Can you provide a pointer to the documentation for the following please?

> On generic resource definition, allow the specification of Azure Monitor metric type (Capacity / Transactional).

Haven't heard about those 2 metric types so want to dig into that topic first.

If you are talking about [this](https://docs.microsoft.com/en-us/azure/storage/common/storage-metrics-in-azure-monitor#transaction-metrics) then I think this is Azure storage specific unless `Capacity` & `Transactional` are just examples of metrics which you can query

**Comment by jdevalk2** [comment]
@tomkerkhove 
You are right that Capacity and Transaction are related to Storage account metrics and not to all Azure Monitor resources in general.  I found that myself, I was having a bit of a tunnel vision on the Storage account when thinking about this PR.

I have been thinking about this and to my other comment at capturing things at the lowest resolution, instead of having a metric type of "transactional", "capacity"  define it more generally such that you can say: 
"lowest", or a timespan "01:00:00" etc.

Lowest:
In which case Promitor will query the metric and choose the lowest data granularity available. Thus producing the highest "resolution" of data.

Timespan:
Promitor will query the metric with the specified data granularity window, and choose the latest value that comes back. It will go back in time for a limited window in which Azure Monitor can be expected to have updated the value.

For 1-minute granularity, 20 minutes
For 1 hour granularity, 2 hours
For 15 minute granularity, 2 hours

**Comment by tomkerkhove** [comment]
That's good to hear, from that perspective we can ignore those changes as it works as intended.

For the scraping timings & metrics aggregation, I would first agree on specs in #198 before implementing anything.

**Comment by jdevalk2** [comment]
Agree pull request should be specific for #198, so this PR can be closed.
In my branch I have reduced the change set to just making the data granularity configurable. This can kick off any discussion on #198.

This is what I am using at the moment I can make a new PR for #198 once it is specced out.

**Pull request closed without merging**
