### PR TITLE
fix: Fix Broken OTEL Sink

### PR DESCRIPTION
**Pull request by hkfgo**
Fixes #

### CODE REVIEW

**Comment by hkfgo** [comment]
```
{"level":"debug","ts":1730420564.6911237,"caller":"prometheusexporter@v0.103.0/accumulator.go:305","msg":"metric expired: promitor_scrape_error","kind":"exporter","data_type":"metrics","name":"prometheus"}
{"level":"debug","ts":1730420564.6911287,"caller":"prometheusexporter@v0.103.0/accumulator.go:305","msg":"metric expired: application_insights_availability","kind":"exporter","data_type":"metrics","name":"prometheus"}
{"level":"debug","ts":1730420564.6911335,"caller":"prometheusexporter@v0.103.0/accumulator.go:305","msg":"metric expired: promitor_demo_servicebus_messagecount_limited","kind":"exporter","data_type":"metrics","name":"prometheus"}
{"level":"debug","ts":1730420564.6911385,"caller":"prometheusexporter@v0.103.0/accumulator.go:305","msg":"metric expired: promitor_scrape_success","kind":"exporter","data_type":"metrics","name":"prometheus"}
{"level":"debug","ts":1730420564.6911428,"caller":"prometheusexporter@v0.103.0/accumulator.go:305","msg":"metric expired: promitor_scrape_success","kind":"exporter","data_type":"metrics","name":"prometheus"}
{"level":"debug","ts":1730420564.691147,"caller":"prometheusexporter@v0.103.0/accumulator.go:305","msg":"metric expired: promitor_demo_servicebus_messagecount_limited","kind":"exporter","data_type":"metrics","name":"prometheus"}
{"level":"debug","ts":1730420564.6911511,"caller":"prometheusexporter@v0.103.0/accumulator.go:305","msg":"metric expired: promitor_demo_servicebus_messagecount_discovered","kind":"exporter","data_type":"metrics","name":"prometheus"}
{"level":"debug","ts":1730420564.6911554,"caller":"prometheusexporter@v0.103.0/accumulator.go:305","msg":"metric expired: promitor_demo_servicebus_messagecount_discovered","kind":"exporter","data_type":"metrics","name":"prometheus"}
{"level":"debug","ts":1730420564.6911595,"caller":"prometheusexporter@v0.103.0/accumulator.go:305","msg":"metric expired: promitor_scrape_error","kind":"exporter","data_type":"metrics","name":"prometheus"}
{"level":"debug","ts":1730420564.691164,"caller":"prometheusexporter@v0.103.0/accumulator.go:305","msg":"metric expired: promitor_scrape_error","kind":"exporter","data_type":"metrics","name":"prometheus"}
{"level":"debug","ts":1730420564.6911705,"caller":"prometheusexporter@v0.103.0/accumulator.go:305","msg":"metric expired: promitor_demo_servicebus_messagecount_discovered","kind":"exporter","data_type":"metrics","name":"prometheus"}
{"level":"debug","ts":1730420564.691177,"caller":"prometheusexporter@v0.103.0/accumulator.go:305","msg":"metric expired: promitor_demo_servicebus_messagecount_discovered","kind":"exporter","data_type":"metrics","name":"prometheus"}
{"level":"debug","ts":1730420564.6911826,"caller":"prometheusexporter@v0.103.0/accumulator.go:305","msg":"metric expired: promitor_demo_servicebus_messagecount_discovered","kind":"exporter","data_type":"metrics","name":"prometheus"}
{"level":"debug","ts":1730420564.6911886,"caller":"prometheusexporter@v0.103.0/accumulator.go:305","msg":"metric expired: promitor_demo_servicebus_messagecount_discovered","kind":"exporter","data_type":"metrics","name":"prometheus"}
{"level":"debug","ts":1730420820.6947937,"caller":"prometheusexporter@v0.103.0/collector.go:363","msg":"collect called","kind":"exporter","data_type":"metrics","name":"prometheus"}
{"level":"debug","ts":1730420820.6948566,"caller":"prometheusexporter@v0.103.0/accumulator.go:296","msg":"Accumulator collect called","kind":"exporter","data_type":"metrics","name":"prometheus"}
{"level":"debug","ts":1730421332.70311,"caller":"prometheusexporter@v0.103.0/collector.go:363","msg":"collect called","kind":"exporter","data_type":"metrics","name":"prometheus"}
{"level":"debug","ts":1730421332.7031589,"caller":"prometheusexporter@v0.103.0/accumulator.go:296","msg":"Accumulator collect called","kind":"exporter","data_type":"metrics","name":"prometheus"}
```
Check these out @tomkerkhove, I think we'd found the culprit

**Review by tomkerkhove — APPROVED** [review]

**Comment by hkfgo** [comment]
@tomkerkhove we should be good to go here!

**Pull request merged**
