### PR TITLE
Promitor should log and keep track of rate limit

### LINKED ISSUE #199: Promitor should handle or log when rate limit is detected
Azure Monitor and more largely Azure Resource Monitor has a feature rate limit, that will limit the amount of requests to 15000 per hour, per ARM instance.

When requesting Azure Monitor you can see the rate limit decrease.

In cases where there are lots of ARM operations going on and Promitor is configured to query lots of resources, potentially it could happen that a rate limit is exceeded.

Therefore users need to be aware that the rate limit exists when configuring, and Promitor should handle the rate limit gracefully possible logging a clear message like "Rate limit exceeded" 

Each ARM response will have a X-Rate-Limit-* or similar HTTP headers and it will list the number of operations that are still possible with ARM. 

I have not looked at the Azure Monitor query API but hopefully they throw this as an exception
If it does then just need to make sure the exception message is clear and that the exceptions would show up outside of Application Insights as well, the channel where Promitor logs its exceptions to at the moment.

### PR DESCRIPTION
**Pull request by cnadolny**
Fixes #199

## Proposed Changes

  - Promitor will log when rate limit is reached.
  - Number of remaining API calls (subscription wide) will be available via health endpoint.
  - StorageQueueScraper is not able to be updated, as the API has not yet been updated to allow passing in a delegating handler to the client.
      - https://github.com/Azure/azure-storage-net/blob/8c426573fda5c0caa6704a2d0f9af0acef0e7b9f/Lib/Common/Queue/Account/AccountExtensions.cs

### CODE REVIEW

**Comment by tomkerkhove** [comment]
Thanks for your PR! Added a comment in #199 on the expected outcome for this and will review after that once we've agreed on it.

**Comment by tomkerkhove** [comment]
@cnadolny It looks like you're using `x-ms-ratelimit-remaining-subscription-reads`, is there any other info than this that can be interesting?

**Comment by tomkerkhove** [comment]
Feel free to let me know if I should re-review once you've made the required changes @cnadolny

**Comment by cnadolny** [comment]
> 
> 
> Feel free to let me know if I should re-review once you've made the required changes @cnadolny

Sounds good! I think the changes discussed on the other thread make sense. I'll make the according changes soon.

**Comment by tomkerkhove** [comment]
Do you need a hand on this PR @cnadolny or shall I take over?

**Comment by tomkerkhove** [comment]
Let me know if you need some help @cnadolny - If you're not able to proceed with this in 7 days I'll have to take over given we'd like to ship v1.0.0.

If that would be the case, don't take it as an offense and I do appreciate the work you've already done!

/remind me in 7 days to take this over unless @cnadolny is able to pick it up before then.

**Comment by tomkerkhove** [comment]
/remind me in 7 days to take this over unless @cnadolny is able to pick it up before then.

**Comment by cnadolny** [comment]
> 
> 
> /remind me to take this over unless @cnadolny is able to pick it up before then in 7 days

Hey Tom - so sorry, kept meaning to get to this but haven't had the time. Please pick it up from me!

**Comment by tomkerkhove** [comment]
No problem @cnadolny, thanks for the contribution anyway!

**Pull request closed without merging**
