### PR TITLE
Implementation of Cosmos DB scraper

### PR DESCRIPTION
**Pull request by cesar-younes**
### Fixes
Changed 1 word in the documentation adding-a-new-scraper.md

### Proposed Changes
 - Added CosmosDB Scraper

### CODE REVIEW

**Comment by brusMX** [comment]
@cesar-younes your tests are failing in the CI. Could you please add your own tests and make sure the current tests don't fail?

**Comment by cesar-younes** [comment]
fixed unit test

**Comment by brandonh-msft** [comment]
@cesar-younes JIC you're having trouble finding the issue that's causing the CI to fail:
~~~
##[warning]Promitor.Core.Scraping\Configuration\Model\Metrics\ResourceTypes\CosmosDbMetricDefinition.cs(,1): warning : R# Using directive is not required by the code and can be safely removed
##[warning]Promitor.Core.Scraping\Configuration\Model\Metrics\ResourceTypes\CosmosDbMetricDefinition.cs(2,1): warning : R# Using directive is not required by the code and can be safely removed
##[warning]Promitor.Core.Scraping\Configuration\Model\Metrics\ResourceTypes\CosmosDbMetricDefinition.cs(3,1): warning : R# Using directive is not required by the code and can be safely removed
~~~

**Comment by cesar-younes** [comment]
pulled latest which was 76e8b37 then merged my changes and committed again

**Comment by tomkerkhove** [comment]
Thank you @cesar-younes!

**Pull request merged**
