### PR TITLE
Support for Azure Database for PostgreSQL resource type

### LINKED ISSUE #322: Provide support for scraping metrics for Azure Database for PostgreSQL
Provide support for scraping metrics for Azure Database for PostgreSQL

### PR DESCRIPTION
**Pull request by jcorioland**
Fixes #322 

Work in progress:

- [x] Configuration for the new `PostgreSql` resource type
- [x] Tests for serialization/deserialization
- [x] Validator and tests for the new `PostgreSql` resource type
- [x] Scraper for the new `PostgreSql` resource type
- [x] Documentation
- [x] Tests in cluster

### CODE REVIEW

**Comment by jcorioland** [comment]
Hi @tomkerkhove - I've made good progress on the implementation of the scraper of Azure Database for PostgreSQL and I would like your opinion on the following:

There is currently a new PostgreSQL hyperscale offer in preview (see [here](https://docs.microsoft.com/en-us/azure/postgresql/overview#azure-database-for-postgresql---hyperscale-citus-preview)). 

That means that  there are two endpoints available for Az Monitor metrics (see [here](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/metrics-supported#microsoftdbforpostgresqlservers)): `/servers` and `/serversv2`. 

This PR currently supports only v1.

In my opinion we can handle it in the same scraper, introducing a version variable into the configuration.

Something like that:

```yaml
name: postgre_sql_cpu_percent
description: "The CPU percentage on the server"
resourceType: PostgreSql
serverName: Promitor
version: v2
scraping:
  schedule: "0 */2 * ? * *"
azureMetricConfiguration:
  metricName: cpu_percent
  aggregation:
    type: Average
    interval: 00:01:00
```

What do you think about?

**Comment by tomkerkhove** [comment]
That's a good point.

I presume these are also 2 different types of Azure resources or not?

If they are, I would suggest using one of the following:
1. `PostgreSqlSingleServer` and `PostgreSqlHyperscale`
2. `SingleServerPostgreSql` and `HyperscalePostgreSql`

I like 1) more given it clearly shows it is for PostgreSql before going into detail, but might be odd from a reading perspective.

The reason why I prefer this over version numbers is that this will allow us to better document the configuration and provide the capability, later on, to do breaking changes in existing scrapers by using `version`.

Thoughts?

**Comment by tomkerkhove** [comment]
The PR already looks good but will wait for a sample, although I'm pretty sure it works fine!

**Comment by jcorioland** [comment]
## Tests in clusters

### Configuration

```yaml
metrics:
  - name: cpu_percent
    description: "CPU %"
    resourceType: PostgreSql
    serverName: postgresjco
    scraping:
      schedule: "0 */2 * ? * *"
    azureMetricConfiguration:
      metricName: cpu_percent
      aggregation:
        type: Average
        interval: 00:01:00
  - name: memory_percent
    description: "Memory %"
    resourceType: PostgreSql
    serverName: postgresjco
    scraping:
      schedule: "0 */2 * ? * *"
    azureMetricConfiguration:
      metricName: memory_percent
      aggregation:
        type: Average
        interval: 00:01:00
  - name: io_consumption_percent
    description: "io consumption %"
    resourceType: PostgreSql
    serverName: postgresjco
    scraping:
      schedule: "0 */2 * ? * *"
    azureMetricConfiguration:
      metricName: io_consumption_percent
      aggregation:
        type: Average
        interval: 00:01:00
  - name: storage_percent
    description: "Storage %"
    resourceType: PostgreSql
    serverName: postgresjco
    scraping:
      schedule: "0 */2 * ? * *"
    azureMetricConfiguration:
      metricName: storage_percent
      aggregation:
        type: Average
        interval: 00:01:00
  - name: storage_used
    description: "Storage used (bytes)"
    resourceType: PostgreSql
    serverName: postgresjco
    scraping:
      schedule: "0 */2 * ? * *"
    azureMetricConfiguration:
      metricName: storage_used
      aggregation:
        type: Average
        interval: 00:01:00
  - name: storage_limit
    description: "Storage limit (bytes)"
    resourceType: PostgreSql
    serverName: postgresjco
    scraping:
      schedule: "0 */2 * ? * *"
    azureMetricConfiguration:
      metricName: storage_limit
      aggregation:
        type: Average
        interval: 00:01:00
  - name: serverlog_storage_percent
    description: "Server logs Storage %"
    resourceType: PostgreSql
    serverName: postgresjco
    scraping:
      schedule: "0 */2 * ? * *"
    azureMetricConfiguration:
      metricName: serverlog_storage_percent
      aggregation:
        type: Average
        interval: 00:01:00
  - name: serverlog_storage_usage
    description: "Server logs Storage used (bytes)"
    resourceType: PostgreSql
    serverName: postgresjco
    scraping:
      schedule: "0 */2 * ? * *"
    azureMetricConfiguration:
      metricName: serverlog_storage_usage
      aggregation:
        type: Average
        interval: 00:01:00
  - name: serverlog_storage_limit
    description: "Server logs Storage limit (bytes)"
    resourceType: PostgreSql
    serverName: postgresjco
    scraping:
      schedule: "0 */2 * ? * *"
    azureMetricConfiguration:
      metricName: serverlog_storage_limit
      aggregation:
        type: Average
        interval: 00:01:00
  - name: active_connections
    description: "Active connections count"
    resourceType: PostgreSql
    serverName: postgresjco
    scraping:
      schedule: "0 */2 * ? * *"
    azureMetricConfiguration:
      metricName: active_connections
      aggregation:
        type: Count
        interval: 00:01:00
  - name: connections_failed
    description: "Failed connection count"
    resourceType: PostgreSql
    serverName: postgresjco
    scraping:
      schedule: "0 */2 * ? * *"
    azureMetricConfiguration:
      metricName: connections_failed
      aggregation:
        type: Count
        interval: 00:01:00
  - name: backup_storage_used
    description: "Backup storage used (bytes)"
    resourceType: PostgreSql
    serverName: postgresjco
    scraping:
      schedule: "0 */2 * ? * *"
    azureMetricConfiguration:
      metricName: backup_storage_used
      aggregation:
        type: Average
        interval: 00:01:00
  - name: network_bytes_egress
    description: "Network bytes egress (bytes)"
    resourceType: PostgreSql
    serverName: postgresjco
    scraping:
      schedule: "0 */2 * ? * *"
    azureMetricConfiguration:
      metricName: network_bytes_egress
      aggregation:
        type: Total
        interval: 00:01:00
  - name: network_bytes_ingress
    description: "Network bytes ingress (bytes)"
    resourceType: PostgreSql
    serverName: postgresjco
    scraping:
      schedule: "0 */2 * ? * *"
    azureMetricConfiguration:
      metricName: network_bytes_ingress
      aggregation:
        type: Total
        interval: 00:01:00
  - name: pg_replica_log_delay_in_seconds
    description: "replica log delay in seconds"
    resourceType: PostgreSql
    serverName: postgresjco
    scraping:
      schedule: "0 */2 * ? * *"
    azureMetricConfiguration:
      metricName: pg_replica_log_delay_in_seconds
      aggregation:
        type: Maximum
        interval: 00:01:00
  - name: pg_replica_log_delay_in_bytes
    description: "replica log delay in bytes"
    resourceType: PostgreSql
    serverName: postgresjco
    scraping:
      schedule: "0 */2 * ? * *"
    azureMetricConfiguration:
      metricName: pg_replica_log_delay_in_bytes
      aggregation:
        type: Maximum
        interval: 00:01:00
```

### /metrics output results

```
# HELP active_connections Active connections count
# TYPE active_connections gauge
active_connections{resource_uri="subscriptions/0000-0000000-000000000/resourceGroups/promitor-rg/providers/Microsoft.DBforPostgreSQL/servers/postgresjco"} 2 1561109055433
# HELP backup_storage_used Backup storage used (bytes)
# TYPE backup_storage_used gauge
backup_storage_used{resource_uri="subscriptions/0000-0000000-000000000/resourceGroups/promitor-rg/providers/Microsoft.DBforPostgreSQL/servers/postgresjco"} -1 1561109053492
# HELP connections_failed Failed connection count
# TYPE connections_failed gauge
connections_failed{resource_uri="subscriptions/0000-0000000-000000000/resourceGroups/promitor-rg/providers/Microsoft.DBforPostgreSQL/servers/postgresjco"} 0 1561109055478
# HELP cpu_percent CPU %
# TYPE cpu_percent gauge
cpu_percent{resource_uri="subscriptions/0000-0000000-000000000/resourceGroups/promitor-rg/providers/Microsoft.DBforPostgreSQL/servers/postgresjco"} 0 1561109055130
# HELP io_consumption_percent io consumption %
# TYPE io_consumption_percent gauge
io_consumption_percent{resource_uri="subscriptions/0000-0000000-000000000/resourceGroups/promitor-rg/providers/Microsoft.DBforPostgreSQL/servers/postgresjco"} 0 1561109052002
# HELP memory_percent Memory %
# TYPE memory_percent gauge
memory_percent{resource_uri="subscriptions/0000-0000000-000000000/resourceGroups/promitor-rg/providers/Microsoft.DBforPostgreSQL/servers/postgresjco"} 0 1561109053542
# HELP network_bytes_egress Network bytes egress (bytes)
# TYPE network_bytes_egress gauge
network_bytes_egress{resource_uri="subscriptions/0000-0000000-000000000/resourceGroups/promitor-rg/providers/Microsoft.DBforPostgreSQL/servers/postgresjco"} -1 1561109053328
# HELP network_bytes_ingress Network bytes ingress (bytes)
# TYPE network_bytes_ingress gauge
network_bytes_ingress{resource_uri="subscriptions/0000-0000000-000000000/resourceGroups/promitor-rg/providers/Microsoft.DBforPostgreSQL/servers/postgresjco"} -1 1561109054828
# HELP pg_replica_log_delay_in_bytes replica log delay in bytes
# TYPE pg_replica_log_delay_in_bytes gauge
pg_replica_log_delay_in_bytes{resource_uri="subscriptions/0000-0000000-000000000/resourceGroups/promitor-rg/providers/Microsoft.DBforPostgreSQL/servers/postgresjco"} -1 1561109055443
# HELP pg_replica_log_delay_in_seconds replica log delay in seconds
# TYPE pg_replica_log_delay_in_seconds gauge
pg_replica_log_delay_in_seconds{resource_uri="subscriptions/0000-0000000-000000000/resourceGroups/promitor-rg/providers/Microsoft.DBforPostgreSQL/servers/postgresjco"} -1 1561109052213
# HELP promitor_ratelimit_arm Indication how many calls are still available before Azure Resource Manager is going to throttle us.
# TYPE promitor_ratelimit_arm gauge
promitor_ratelimit_arm{tenant_id="72f988bf-86f1-41af-91ab-2d7cd011db47",subscription_id="0000-0000000-000000000",app_id="564689e4-9f02-4f9a-9253-a6c3e837d630"} 11958 1561109054970
# HELP serverlog_storage_limit Server logs Storage limit (bytes)
# TYPE serverlog_storage_limit gauge
serverlog_storage_limit{resource_uri="subscriptions/0000-0000000-000000000/resourceGroups/promitor-rg/providers/Microsoft.DBforPostgreSQL/servers/postgresjco"} 1073741824 1561109052229
# HELP serverlog_storage_percent Server logs Storage %
# TYPE serverlog_storage_percent gauge
serverlog_storage_percent{resource_uri="subscriptions/0000-0000000-000000000/resourceGroups/promitor-rg/providers/Microsoft.DBforPostgreSQL/servers/postgresjco"} 0 1561109054574
# HELP serverlog_storage_usage Server logs Storage used (bytes)
# TYPE serverlog_storage_usage gauge
serverlog_storage_usage{resource_uri="subscriptions/0000-0000000-000000000/resourceGroups/promitor-rg/providers/Microsoft.DBforPostgreSQL/servers/postgresjco"} 23016 1561109054836
# HELP storage_limit Storage limit (bytes)
# TYPE storage_limit gauge
storage_limit{resource_uri="subscriptions/0000-0000000-000000000/resourceGroups/promitor-rg/providers/Microsoft.DBforPostgreSQL/servers/postgresjco"} 107374182400 1561109053204
# HELP storage_percent Storage %
# TYPE storage_percent gauge
storage_percent{resource_uri="subscriptions/0000-0000000-000000000/resourceGroups/promitor-rg/providers/Microsoft.DBforPostgreSQL/servers/postgresjco"} 0.02 1561109054094
# HELP storage_used Storage used (bytes)
# TYPE storage_used gauge
storage_used{resource_uri="subscriptions/0000-0000000-000000000/resourceGroups/promitor-rg/providers/Microsoft.DBforPostgreSQL/servers/postgresjco"} 16851768 1561109054149
```

**Comment by jcorioland** [comment]
@tomkerkhove yeah, after doing a few tests and reading the documentation about the hyperscale preview, I think it finally makes sense to handle it in another resource, as there are multiple servers to monitor.

We can imagine to have a collection of server inside the configuration to be able to get all the metrics in the same scraper at one time.

I propose that we keep the `PostgreSql` (I don't think we need to specify Single for this one, the service is PostgreSQL in Azure) resource type for this PR, and that we open another issue to create an `PostgreSqlHyperscale` resource type/scraper.

Works for you?

**Comment by tomkerkhove** [comment]
Sounds good to me!

**Comment by tomkerkhove** [comment]
I believe this PR is ready and no longer work-in-progress, is that correct @jcorioland?

**Comment by jcorioland** [comment]
Indeed it is. Was just waiting if I needed to rename the resource type or not. Everything is good on my side.

**Comment by tomkerkhove** [comment]
Thank you very much for your contribution @jcorioland 	!

**Pull request merged**
