### PR TITLE
Starter scraper config for Azure resources

### PR DESCRIPTION
**Pull request by jkataja**
Adds starter configuration files for Azure resources:

 - Cosmos DB usage, RUs consumption, latency and availability metrics
 - Key Vault latency, saturation and availability metrics
 - Blob Storage API requests, data, latency and availability metrics
 - Virtual Machine Scale Set (VMSS) CPU, disk and network usage metrics

### CODE REVIEW

**Comment by JanneKataja-TomTom** [comment]
I need to complete a process to clear the CLA before I can accept it

**Comment by tomkerkhove** [comment]
Let me know if you are good to go!

I'm wondering - Do you prefer them here or on Promitor.io? They could be on pages such as https://promitor.io/configuration/v2.x/metrics/Cosmos-DB?

**Comment by jkataja** [comment]
Either one should work. Maybe they would be easier to discover from the documentation.

**Comment by tomkerkhove** [comment]
Let's do that but I'm happy to move it for you once the PR is merged.

**Pull request merged**
