### PR TITLE
test: Add unit tests for Graph Query Builder

### LINKED ISSUE #1166: Provide unit tests for Azure Resource Graph query builder
Provide unit tests for query builder.

Follow-Up of #512

### PR DESCRIPTION
**Pull request by mohaemen**
Fixes #1166

### CODE REVIEW

**Comment by mohaemen** [comment]
> Thanks for the PR! You can ignore the build issues on the container image, this is something I need to fix - Sorry!
> 
> Let me know when it's ready for review.

Alright, no worries, I wasn't sure about them, so I moved the PR to draft.
Will move to PR again.

**Comment by tomkerkhove** [comment]
No problem! The new tests are failing though. Would you mind adding an OS-agnostic way for the new lines please? Our tests run on LInux.

**Review by tomkerkhove — APPROVED** [review]
LGTM, thanks a ton!

**Comment by tomkerkhove** [comment]
@mohaemen It looks like the commits are done with 2 users, would you mind force pushing with @mohaemen as a user please? Otherwise the CLA check won't pass.

**Comment by mohaemen** [comment]
@tomkerkhove Yeah, the push was from work laptop :D 
I forced pushed with my github user

**Comment by tomkerkhove** [comment]
Thank you!

**Comment by mohaemen** [comment]
@tomkerkhove No worries 👍

**Comment by mohaemen** [comment]
@tomkerkhove one thing I noticed while working on this, the Operator.DoesNotEquals, shouldn't it be Operator.DoesNotEqual without the 's' at the end?

**Comment by tomkerkhove** [comment]
That can be an improvement, yes.

**Pull request merged**
