### PR TITLE
Allow for Metric Scraping interval to be defined overall & per-metric via YAML config

### LINKED ISSUE #258: Provide capability to configure the scraping interval per metric
Metrics do not always need to be scraped with the same frequency.

We should provide the capability to configure the scraping interval per metric.

Once this is implemented every metric that is being scraped should be fully isolated from each other. That means if we scrap A, B & C and B fails, A & C should still be tracked.

### Checklist
In order to achieve this we will:
- [x] Configure the scraping interval via `scraping.interval`
- [ ] Use configured scraping interval per metric
- [ ] Update documentation on how to configure this

### Metrics Specification

```yaml
azureMetadata:
  tenantId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
  subscriptionId: yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy
  resourceGroupName: promitor
metrics: 
  - name: demo_queue_size
    description: "Amount of active messages of the 'myqueue' queue"
    resourceType: ServiceBusQueue
    namespace: promitor-messaging
    queueName: orders
    scraping:
      interval: <interval>
```

### Other
Closes #60 and #198

### PR DESCRIPTION
**Pull request by brandonh-msft**
Fixes #258 & #259 

This PR accomplishes the following:
* Move metric scraping schedule from Env variables -> YAML configuration under `metricDefaults.scraping.schedule`
* Allow for an individual metric to have `<metric>.scraping.schedule` defined, overriding the value specified in `metricDefaults`
* **Require** `metricDefaults.scraping.schedule` as part of validation
* Adds a unit test to verify that validation fails if no default schedule is given in the YAML file
* Reads the YAML config file at startup and spins up a `MetricScrapingJob` instance for every metric defined, with the correct schedule (inherited from default, overriden in metric def). **I confirmed they all run in parallel on their correct schedules** in my local testing 🎉

In addition to these features added, it changes the behavior of the **Scraper** to no longer require `MetricDefaults` as the `MetricDeclarationProvider` now supports an `applyDefaults` parameter on its `Get()` method (`false` by default; up for debate IMO) which will, when furnishing individual metrics, apply values in `metricDefaults` to any properties which don't have values in the metric itself. This isolates the scraper from needing to know how/when to do this.

### CODE REVIEW

**Comment by brandonh-msft** [comment]
don't merge - i forgot to update adding-a-scraper docs

**Comment by brandonh-msft** [comment]
forgot docs

**Comment by brandonh-msft** [comment]
anybody know why the `snyk` steps wouldn't be running for this right now?

cc @tomkerkhove

**Comment by brandonh-msft** [comment]
@tomkerkhove not sure why but we have 1 approving review and it still won't let us merge the PR. 🤷🏻‍♂️

**Comment by brandonh-msft** [comment]
@jsturtevant could you approve this and see if we can get "Squash & merge" to light up for us?

**Comment by tomkerkhove** [comment]
Thanks @brandonh-msft 	!

**Pull request merged**
