### PR TITLE
fix: Multi dimension support for StatsD

### PR DESCRIPTION
**Pull request by SagiVaknin**
Fixes #

### CODE REVIEW

**Review by tomkerkhove — APPROVED** [review]

**Comment by SagiVaknin** [comment]
@tomkerkhove, seems like there is some transient issue with the openTelemetry sink tests.
If you can retrigger the pipeline.

We also noticed some issues with the opentelemetry sink in some of our promitor instances, not so familiar with openTelemetry
but generally, we noticed that it stops emitting the metrics to the opentelemetry container at some point.
started some small investigation but it seems maybe some kind of deadlock? or reaching a stuck state.

**Comment by tomkerkhove** [comment]
> We also noticed some issues with the opentelemetry sink in some of our promitor instances, not so familiar with openTelemetry
> but generally, we noticed that it stops emitting the metrics to the opentelemetry container at some point.
> started some small investigation but it seems maybe some kind of deadlock? or reaching a stuck state.

I haven't heard about this from others but feel free to open an issue for this. Would need to have some more details on the exact problem though.

**Comment by tomkerkhove** [comment]
> [CLA assistant check](https://cla-assistant.io/tomkerkhove/promitor?pullRequest=2353) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tomkerkhove/promitor?pullRequest=2353) before we can accept your contribution.
> 
> **Sagi Vaknin** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).
> You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tomkerkhove/promitor?pullRequest=2353) it.

Can you fix the CLA please?

**Comment by SagiVaknin** [comment]
> > [CLA assistant check](https://cla-assistant.io/tomkerkhove/promitor?pullRequest=2353) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tomkerkhove/promitor?pullRequest=2353) before we can accept your contribution.
> > **Sagi Vaknin** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).
> > You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tomkerkhove/promitor?pullRequest=2353) it.
> 
> Can you fix the CLA please?

Always mixing between my account to the MS one, which I can't sign on.
already signed on my personal account

**Comment by tomkerkhove** [comment]
No worries. Can you try doing a force push with your personal account please? That should fix it

**Comment by tomkerkhove** [comment]
Looks like we still have 2 users that need to sign the CLA, can you please try again @SagiVaknin?

**Pull request closed without merging**
