### PR TITLE
chore(deps): Update Prometheus.Client to v4.3.0

### PR DESCRIPTION
**Pull request by sanych-sun**
Bump Prometheus.Client and resolve breaking change

### CODE REVIEW

**Comment by tomkerkhove** [comment]
Thanks for the chore @sanych-sun! Would you mind signing the CLA please?

**Comment by sanych-sun** [comment]
@tomkerkhove need to read what does that mean.

**Comment by tomkerkhove** [comment]
It's just an MIT CLA agreeing to contribute but feel free to take your time.

Thanks!

**Review by tomkerkhove — APPROVED** [review]

**Comment by tomkerkhove** [comment]
Thanks @sanych-sun!

**Pull request merged**
