### PR TITLE
chore(deps): Add group for Prometheus.Client in Renovate config

### PR DESCRIPTION
**Pull request by phnx47**
Combine update all Prometheus.Client packages into one PR

### CODE REVIEW

**Review by tomkerkhove — APPROVED** [review]
Thanks a ton!

**Comment by phnx47** [comment]
@tomkerkhove Yes, I can find next month.

**Comment by tomkerkhove** [comment]
Thank you!

**Comment by tomkerkhove** [comment]
Did you consider PRing a preset in to Renovate?

https://github.com/renovatebot/renovate/tree/main/lib/config/presets/internal

**Pull request merged**
