### PR TITLE
chore: Provide initial mkdocs setup for new docs.promitor.io (🏗️)

### PR DESCRIPTION
**Pull request by smholvoet**
Related to #540

### CODE REVIEW

**Comment by tomkerkhove** [comment]
Feel free to change `netlify.toml`  to use Mkdocs https://docs.netlify.com/configure-builds/common-configurations/#mkdocs

**Comment by tomkerkhove** [comment]
Happy new year! Just checking in to see if I can help you with anything or if you prefer me to take over?

**Comment by tomkerkhove** [comment]
Any thoughts on this @smholvoet?

**Comment by smholvoet** [comment]
@tomkerkhove 

Hi, been a while. So how would you want me to proceed? Start with updating `netlify.toml` first?

**Comment by tomkerkhove** [comment]
I'd rather ask you - If you say this current state is a good boilerplate and just needs content migration, then I think I can pick that up. The only thing I'd love to have is some help on the Netlify configuration and/or some docs on how to run it locally.

Does that sound reasonable?

**Comment by smholvoet** [comment]
Sounds good. Don't have any experience with Netlify but I'll see what I can do.

Regarding running the docs locally, I'll add a dedicated page for that so it's easier for docs contributors to test out their changes. In case you want to try things out, here's a short summary:

1. Install Python:
    ```
    choco install python
    ```

2. Install mkdocs and related packages from a `requirements.txt` file (this gets added to the root of the repo) which would look like this:

    **requirements.txt:**
    ```
    mkdocs-material
    openpyxl
    ```
    
    Install all Python packages mentioned in the above file:
    ```
    pip install -r requirements.txt
    ```
  
    The above command will install (see [this](https://squidfunk.github.io/mkdocs-material/getting-started/) link for more info):
    
      - MkDocs
      - Markdown
      - Pygments
      - Python Markdown Extensions
      - 3rd-party plugins


3. Run the docs locally"

    - Clone this repo
    - Run `mkdocs serve`
    - Wait for the site to build and navigate to [`http://127.0.0.1:8000/`](http://127.0.0.1:8000/)

**Comment by tomkerkhove** [comment]
That would be nice, thank you!

If you don't have experience with Netlify then I'll take a look at it - No worries!

**Comment by tomkerkhove** [comment]
Merging to temp branch to setup netlify - Feel free to PR the docs in there.

Thank you!

**Pull request merged**
